kind: pipeline
type: docker
name: build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  - name: pull-ros
    image: localhost:5000/ros:galactic
    pull: always
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo "Pull image for build"

  - name: builder-rosdep
    image: plugins/docker
    network_mode: "host"
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    pull: if-not-exists
    settings:
      repo: localhost:5000/rmf/builder-rosdep
      registry: localhost:5000
      dockerfile: builder-rosdep.Dockerfile

trigger:
  branch:
    - build/builder-rosdep
