kind: pipeline
type: docker
name: build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  - name: builder-nginxhello
    image: plugins/docker
    network_mode: "host"
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      repo: 10.0.2.3:5000/ nginxhello
      registry: 10.0.2.3:5000
      dockerfile: nginx-hello/Dockerfile

trigger:
  branch:
    - main
    - demo/*
